# 🛡️ NUSANTARA MAIN GRADLE PROPERTIES
android.useAndroidX=true
android.enableJetifier=true
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
android.suppressUnsupportedCompileSdk=35
org.gradle.jvmargs=-Xmx4G -Dkotlin.daemon.jvm.options="-Xmx2G"
org.gradle.parallel=true
org.gradle.caching=true
