# Edit file ini: nano key.properties
storePassword=123abc!
keyPassword=123abc!
keyAlias=azura
storeFile=/home/max/azuratime/nusantara-main/app/azura-key.jks
MAPS_API_KEY=AIzaSyDjuYor29vzIS_7UWv60pLF80A4p6jXjdc
GEMINI_API_KEY=AIzaSyCFC_OB7mtD6zItLs7UWiZuRotmy9YXYJQ
